### ISSUE TITLE
Mouse up/down events are not passed to the DOM

### ISSUE THREAD

**Issue by MillerGregor** [necolas/react-native-web#1008]
In prior versions, I could set `onMouseDown` on a \<View>, and the generated \<div> would receive the proper `onmousedown` listener.

With changes in 0.8.x, the event listener prop does not get passed.

**How to reproduce**
Simplified test case:

Here's an example with 0.8.5:
https://codesandbox.io/s/rj89zl2onm

Here's 0.7.3:
https://codesandbox.io/s/w2v6xxy2yl

Also, the 2048 game is affected:
http://necolas.github.io/react-native-web/storybook/?selectedKind=Example%20apps&selectedStory=Game2048&full=0&addons=0&stories=1&panelRight=0
... although it does correctly pass the touch events.

Steps to reproduce:
1.  create a \<View>
2.  assign a function to `onMouseDown`
3.  function is not called when mouse is down over  \<View>

**Expected behavior**
The function is called when the \<View>'s \<div> is clicked

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.5
* React (version): 16.3.1
* Browser: chrome 67

**Additional context**
I'm sure this is related the PanResponder fixes.

While not ideal, I can work with a primary button click being a touch in the eyes of PanResponder, but middle- and right-clicks are needed.  Specifically, my custom three.js orbitControls component needs middle- and right-button mouse events for zoom and pan.  The native side uses multi-finger touches.

**Comment by necolas** [comment]
The additional context is about the responder system and doesn't seem related to the missing mouse events.

**Comment by Gregor1971** [comment]
Need `move` in addition to `up `& `down`

**Comment by necolas** [comment]
Oh is the additional context saying that you're using mouse events directly because the responder events don't include middle and right mouse? Yeah I think using mouse directly make sense for those kinds of specific mouse interactions, especially when providing a mouse equivalent to multi-touch interactions.

If you want, you can create the patch that adds the 2 missing mouse events to that whitelist. If not, I'll fix it next time I'm on my laptop
