### ISSUE TITLE
Text: onLongPress support

### ISSUE THREAD

**Issue by chrisdrackett** [necolas/react-native-web#1011]
**The problem**

When I add a `onLongPress` event to a text node I can't get the event to fire on a long press

**How to reproduce**

Simplified test case: https://codesandbox.io/s/6w34l63jw

Steps to reproduce:
1. Long press on text

**Expected behavior**

console will long "long press!"

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.7.3
* React (version): 16.4.0
* Browser: Safari / Chrome

**Comment by necolas** [comment]
Yes, that's mentioned in the compatibility table https://github.com/necolas/react-native-web#compatibility-with-react-native

**Comment by chrisdrackett** [comment]
Oops! Sorry about that!

**Comment by necolas** [comment]
Decided to close this as "wontfix" because the primitive Text component should be simple and fast, which I don't think is the case when it include built-in touch handling, and it could cause regressions for apps like Twitter Lite https://github.com/necolas/react-native-web/pull/1272#issuecomment-539217703.
