### ISSUE TITLE
Multiline TextInput clear() then focus() adds a newline.

### ISSUE THREAD

**Issue by jpstrikesback** [necolas/react-native-web#1013]
**The problem**
When using a multiline TextInput with blurOnSubmit=true, calling ref.clear() after onSubmitEditing is called and then ref.focus() will add a newline to the input.

**How to reproduce**
See code sandbox here: https://codesandbox.io/s/ox9y54w3q9

Steps to reproduce:
1. Add text to the TextInput (setup as described) and hit enter to submit
2. Call clear() on the TextInput ref
3. Call focus() on the TextInput ref

**Expected behavior**
The text is completely cleared to the default state (i.e. with the placeholder), and the input is focused,
**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.6
* React (version): 16.4.1
* Browser: chrome 67

I've seen this in 0.8.3 & 0.8.6.

**Comment by necolas** [comment]
Thanks, I can prevent the newline being added when submitting, but you should be aware that because you're trying to clear the input synchronously in the callback, the browser doesn't have a chance to update the UI until *after* your code has run. You can avoid this issue (which you might encounter in other situations) by running your code in a `setTimeout` within the callback, so that the browser can update first.

**Comment by jpstrikesback** [comment]
Awesome and thanks for the tip!!
