### ISSUE TITLE
Slider: implementation

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1022]
https://facebook.github.io/react-native/docs/slider

**Comment by piranna** [comment]
https://github.com/jeanregisser/react-native-slider

**Comment by necolas** [comment]
That implementation isn't accessible, RTL-compatible, or performant

**Comment by tafelito** [comment]
what about https://github.com/ismnoiet/react-native-range-slider or https://github.com/ptomasroos/react-native-multi-slider?

**Comment by necolas** [comment]
Slider has moved out of RN core to https://github.com/react-native-community/react-native-slider

**Comment by mikeaustin** [comment]
https://github.com/react-native-community/react-native-slider doesn't work with create-react-app since main points to src/index.js. react-native projects compile node_modules, while create-react-app doesn't. I always feel CRA is too restrictive-it would be nice to allow some form of configuration. There's react-app-rewired, but I'd like something more stable.

**Comment by necolas** [comment]
Open an issue against that repo

**Comment by mikeaustin** [comment]
@necolas I was just adding context to this ticket. But yes, nothing to do here. I was just disappointed that react-native split out their slider from the main branch, and that it doesn't work with CRA/RNW out of the box. I'm using the non-accessible, non-RTL-compatible, non-performant component for now.
