### ISSUE TITLE
TouchableNativeFeedback: implementation

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1024]
Technically this is an Android-only component, but it's a popular interaction type for web apps too.

https://facebook.github.io/react-native/docs/touchablenativefeedback.html

**Comment by simonbuerger** [comment]
Firstly, RNW is awesome - thank you for all your hard work.

Secondly can we leverage external components to achieve this? Eg the official material react-ripple package? https://www.npmjs.com/package/@material/react-ripple

Happy to submit a PR if that's acceptable, thought I'd check first

**Comment by vjsingh** [comment]
Just curious on the state of this as well. Anyone have a recommendation for a Ripple component that uses native CSS transforms instead of a js-based approach?

I'm using react-native-material-ripple right now, but because that uses Animated it runs on the JS thread, which means it is mostly unusable.

Appreciate any advice

**Comment by necolas** [comment]
Closing as these touchable components are now deprecated
