### ISSUE TITLE
image zoom doesnt work

### ISSUE THREAD

**Issue by RupamShaw** [necolas/react-native-web#1062]
**The problem**

i would like to add any of image zoom (react-native-image-view") but its not working
**How to reproduce**

Simplified test case: 

Steps to reproduce:
1.https://glitch.com/edit/#!/paper-quart?path=package.json:1:0 
2.https://codesandbox.io/s/8yxvx52760
3.please let me know how image zooming is possible ? same zoomimg  react-native-image-view working on react native in android .

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: TBC

**Comment by necolas** [comment]
I don't know what "not working" means. Do you mean the build fails? RN packages won't work on those web tools because RN packages often aren't compiled before publishing

https://github.com/necolas/react-native-web/blob/master/packages/website/guides/getting-started.md#web-packaging-for-existing-react-native-apps
