### ISSUE TITLE
compatibility with react-fire

### ISSUE THREAD

**Issue by vladp** [necolas/react-native-web#1089]
**Is your feature request related to a problem? Please describe.**

Announcement of react fire (modernizing React Dom) effort, specifically calls React-native-web.
In the context, that the eventing system will be changed and that React-native-web will need
to find other approaches
(see https://github.com/facebook/react/issues/13525 )

> 
> "
> We can't make some of these changes if we aim to keep exposing the current private React event system APIs for projects like React Native Web. However, React Native Web will need a different strategy regardless because React Fabric will likely move more of the responder system to the native side.
> "

**Describe a solution you'd like**

Wanted to ask @necolas  how we could help, and what  we could do both  for the RNW library, and our own code basis -- to make help RNW  and its ecosystem to transition to this future state.

**Comment by necolas** [comment]
There's nothing to do for a while. The post itself mentions that those changes to React DOM are probably several majors away.

**Comment by nathggns** [comment]
Mate… closing this seems unnecessary?

Have you considered that people trying to decide whether to use RNW or not *now* might be considering how prepared the project and its maintainers might be for future updates to React that are more likely than not to be coming within the lifespan of projects and code being written *now*? And have you considered that immediately closing issues asking to discuss this issue is likely to lead people to the conclusion that the project and its maintainers are not at all prepared for that?

**Comment by necolas** [comment]
Yes thanks. I've dealt with several changes to React over the last few years. And I work at Facebook; everyone involved is aware. There's nothing to discuss here as nothing else has been publicly shared about Fire, which is still in the internal experimental R&D work phase
