### ISSUE TITLE
accessibilityRole crashing as of react-native 0.57

### ISSUE THREAD

**Issue by johakr** [necolas/react-native-web#1110]
**The problem**
`accessibilityRole` is used by react-native-web to chose the appropriate component to be rendered. E.g. `<View accessibilityRole="list" />` would be rendered as an `ul` element. However, this behavior collides with [`react-native`'s `accessibilityRole` implementation introduced in 0.57.0](https://facebook.github.io/react-native/blog/2018/08/13/react-native-accessibility-updates). Using the aforementioned code snippet (`<View accessibilityRole="list" />`) will crash on android, since `list` is no valid role for android.

**How to reproduce**
Steps to reproduce:
1. Try to render `<View accessibilityRole="list" />`
2. Run on any android device

**Expected behavior**
Provide an API to chose the component type rendered in web (e.g. `ul`) without colliding with the react-native API. Maybe by renaming the `accessibilityRole` property.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.9.0
* React (version): 16.5.1
* React Native: 0.57.0

Worked in previous react-native versions.

**Comment by necolas** [comment]
The readme says "compatible with React Native 0.55". And the docs explain that you can use `Platform.OS` to set per-platform values etc in your code.

It would be nice if the native app didn't completely crash just because it doesn't recognise a role. Maybe open an issue against react native to see if they can relax that behaviour
