### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by llllGEM** [necolas/react-native-web#1183]
Hi , you have a great tool for react to use sources for mobile and browser, but could you provide a true getting started guide as with how to use it with CRA for example ?
or the best way to boostrap a cross platform/native app .

Thanks in advance

**Comment by necolas** [comment]
There's one in the docs and linked to in the readme

**Comment by llllGEM** [comment]
Hi, sorry but I know how to read, but your getting started does not mention where to start, and the steps for CRA for example are not explained, there is no steps, what are the steps after creating an app with CRA please.

**Comment by llllGEM** [comment]
Maybe how to use it with the last expo cli as well

**Comment by necolas** [comment]
That's something for expo to document, but I don't think expo supports it atm

**Comment by necolas** [comment]
> what are the steps after creating an app with CRA please

There are no steps. It's aliased by default in CRA

**Comment by llllGEM** [comment]
Then how to integrate a CRA with a React Native app for it to work for browser and mobile. I mean you don't provide any information on how to integrate it. Your users have codebases and project already implemented, It would be nice to have a path to follow. As you won't provide a expo cli getting started, then can you add a scenario with a standard react-native app ?

**Comment by steventilator** [comment]
I would like to add some visibility to this issue.

I am trying to figure out how to implement our React Native app into our existing Django web app by using react-native-web. I read the guides of this package multiple times with an emphasis on the Getting Started guide. But since the Getting Started guide simply lays out its instructions by topic I am kind of lost where to start and what to do next.

Is there a chronology to the instructions? Should I follow the instructions from top to bottom in their order? If so, numbering the topics would be helpful. If not, it would be great to explain why a user needs to follow a certain instruction.

To be more precise, after reading the Getting Started guide I am left with the following questions:
- Do I have to set up a new React web project or can I use my React Native code base?
- How do I find out whether my application needs polyfills?
- If I run the Install instructions, do I still have to run the create-react-app command (topic Starter kits)?
- How do I know if I have a custom setup (topic Module Bundler)? I assume I do.
- How do I know if I need to do the aliasing (topic Babel)? What is meant by "aliasing"?  (I assume it's "translating" react-native to react-dom.)

If all this is common knowledge and does not belong into the documentation, it would be great if anyone could point out some resources where I can fill my knowledge gaps.
