### ISSUE TITLE
Warning: Failed prop type: Invalid prop `children` supplied to `Picker`

### ISSUE THREAD

**Issue by jp928** [necolas/react-native-web#1263]
**Warning: Failed prop type: Invalid prop `children` supplied to `Picker`**

**How to reproduce**

```
<Picker>
  <Picker.Item label="test" />
</Picker>
```

Simplified test case: 

Steps to reproduce:
1. React Native 0.58+
2. Add `<Picker.Item>` and child of `<Picker>`

**Expected behavior**
No warning shows up.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.10.0
* React (version): 16.8.3
* Browser: Chrome
<img width="612" alt="screen shot 2019-03-02 at 12 13 17 pm" src="https://user-images.githubusercontent.com/659612/53674799-9ade9800-3ce4-11e9-9553-687fcc7c600a.png">

**Comment by necolas** [comment]
Link to a codesandbox test case please

**Comment by d4rky-pl** [comment]
Uhhhhh, it took me an hour to debug this!

The reason this is happening is because of `react-hot-loader` wrapping the `Picker.Item` in it's `ES6ProxyComponentFactory`. When it happens, the `child.type !== Picker.Item` check is no longer true because `child.type` has been wrapped.

This is the `Picker.Item`:
<img width="384" alt="Screenshot 2019-04-10 16 07 11" src="https://user-images.githubusercontent.com/284395/55885751-c8074b80-5baa-11e9-95f2-cf5362b798bd.png">

And this is `child.type`:
<img width="837" alt="Screenshot 2019-04-10 16 07 21" src="https://user-images.githubusercontent.com/284395/55885762-ca69a580-5baa-11e9-8508-cb9111043d1a.png">

Notice different `[[FunctionLocation]]` which points to VM97:4 in the latter case, which is react-hot-loader's proxy:

<img width="420" alt="Screenshot 2019-04-10 16 08 52" src="https://user-images.githubusercontent.com/284395/55885854-f84eea00-5baa-11e9-8877-46ac6c76d3fe.png">

@necolas I know I'm supposed to provide a codesandbox test case but this one is super tricky and I've already spent way too much time on this. Would it be possible for you to loosen this check without this test case or should I spend another hour or two creating something reproducible? I have very strong opinions about code failing propTypes in development, even if it's ultimately the library not us 😜

**Comment by NishargShah** [comment]
How to solve that? @d4rky-pl

**Comment by necolas** [comment]
Upgrade to the latest version. There is no runtime `PropTypes` checking anymore

**Comment by NishargShah** [comment]
Ohk, I just found out https://github.com/react-native-community/react-native-picker, I am using the deprecated picker, thanks for the reply :)
