### ISSUE TITLE
FlatList performance: Scrolling is buggy and not smooth when virtualization is enabled

### ISSUE THREAD

**Issue by brunolemos** [necolas/react-native-web#1337]
**The problem**

It have a vertical FlatList with not that many items (~150). When virtualization is enabled and I scroll, there are lot's of FPS loss, I can see the lag clearly. Every time I scroll a little bit and a new dom element is added by the virtualization it happens.

On iOS simulator it's fast and smooth. On chrome is the worse, firefox is less bad but still not good.

If I use `disableVirtualization`, then it becomes super smooth, but it has its consequences, e.g. switching between screens is much more expensive. 

I played with all the virtualization options, didn't help much.

Twitter is quite fast and also has dynamic height, does it use the same FlatList we use? If not, would love if they could open source it.

I've considered react-window but it doesn't seem to support dynamic height (just-in-time measurement) yet. https://github.com/bvaughn/react-window/issues/6. Maybe react-virtualized could help.
The problem is that these external solutions don't support things like `scrollToItem`, `onViewableItemsChanged`, etc :(

### With virtualization enabled + getItemLayout forcing height:100

_Slow and buggy_

![Kapture 2019-05-04 at 22 19 59](https://user-images.githubusercontent.com/619186/57186724-f979eb00-6eba-11e9-8f36-a992ae402567.gif)

### Without virtualization (`disableVirtualization`)

_Scrolling is fast and smooth (screen change / first render is slower; memory usage is higher)_

![Kapture 2019-05-04 at 22 22 22](https://user-images.githubusercontent.com/619186/57186733-23cba880-6ebb-11e9-8e26-893caede2f22.gif)

**Comment by brunolemos** [comment]
You can close this but I'd appreciate some insights.

**Comment by sfcgeorge** [comment]
I also noticed slow FlatList but I don't need dynamic heights so I was able to get good performance. Things to try:

* Use PureComponent for your items.
* Set keyExtractor.
* Set getItemLayout (it's a function so you may be able to calculate dynamic height yourself).

I suspect getItemLayout will fix it for you. Before worrying about how to calculate the height, just set it to something fixed to test if that does solve the performance for you. If yes, then you can work out how to calculate.

I believe FlatList is taken straight from RN so I assume native Views + Yoga perform better than divs + flexbox in browser. Probably not much can be done without rewriting FlatList which I assume is out of scope as RNW tries to stay close to RN. A third party like Twitter could open source theirs (if they have one) but you'd have to ask them `¯⁠\_(ツ)_/⁠¯`

**Comment by brunolemos** [comment]
> PureComponent, keyExtractor

I use that already.

> getItemLayout

Just tried, unfortunately didn't help. Used `getItemLayout` to fix the height in `100`. When scrolling, it still makes small jumps when the virtualization adds new items. The only thing that worked so far was `disableVirtualization`.

**Comment by brunolemos** [comment]
Here's a gif comparison.

### With virtualization enabled + getItemLayout forcing height:100

_Slow and buggy_

![Kapture 2019-05-04 at 22 19 59](https://user-images.githubusercontent.com/619186/57186724-f979eb00-6eba-11e9-8f36-a992ae402567.gif)

### Without virtualization

_Fast and smooth_

![Kapture 2019-05-04 at 22 22 22](https://user-images.githubusercontent.com/619186/57186733-23cba880-6ebb-11e9-8e26-893caede2f22.gif)

But disabling virtualization has its consequences too. Initial screen render is much more expensive, for example. So i'd really like to have a great flatlist virtualization for web.

**Comment by derekblank** [comment]
@brunolemos I have experienced this when a `<FlatList />` nested within a `ScrollView` contains many subviews (especially subviews containing images). 

The [example provided by RNW](https://github.com/necolas/react-native-web/blob/0e81c6ef2758d4ca9b2099b1d04a4f8c417f0f43/packages/examples/src/RNTester/FlatListExample.js#L119-L148) wraps FlatList with `createAnimatedComponent` from the Animated API, and also uses some other methods that may help you.

Also worth noting that while `disableVirtualization` is still active in RNW, it is deprecated in RN.

**Comment by sfcgeorge** [comment]
I think the answer is use `React.PureComponent` for all renderItem, ItemSeparatorComponent, ListHeaderComponent, etc. The example's item component uses PureComponent here: https://github.com/necolas/react-native-web/blob/0e81c6ef2758d4ca9b2099b1d04a4f8c417f0f43/packages/examples/src/RNTester/ListExampleShared.js#L45

It certainly seems to fix my code, for both FlatList and SegmentedList. A simpler example:

```js
class FilterItem extends React.PureComponent {
  render() {
    const { item, index } = this.props
    return <Text key={index}>{item}</Text>
  }
}

class FilterSeparator extends React.PureComponent {
  render() {
    return <View />
  }
}

export default class SearchFilters extends React.Component {
  render() {
    return (
      <FlatList
        renderItem={({ item, i }) => <FilterItem item={item} index={i} />}
        ItemSeparatorComponent={FilterSeparator}
      />
    )
  }
}
```

**Comment by brunolemos** [comment]
I think it's some kind of bug, I already do all these common optimizations. Also there is no ScrollView above it. It works perfectly on ios and android, problem is only on browser.

**Comment by pcooney10** [comment]
I am not entirely certain, but I think it might have something to do with `FlatList` and `VirtualizedList` not actually being implemented in RNW yet?

FlatList and VirtualizedList seem to be taken directly from react-native, and do not contain any of the DOM specific customizations like we see in [ScrollView](https://github.com/necolas/react-native-web/tree/master/packages/react-native-web/src/exports/ScrollView), TextInput, and View.

The vendor exports do, however, reference the DOM specific `ScrollView` and `View` components, so maybe that means they are actually implemented.

I think the FlatList performance suggestions in this thread are good, and definitely applicable since React is still managing the tree reconciliation, but may be outweighed by the need for a DOM specific optimization. I am not entirely sure what that optimization is, but I think @brunolemos is on to something with `react-window`. 

As an aside, the `React.PureComponent` optimization really only matters when the component has functional props - i.e. an `onPress` handler  or a `navigate` prop from react-navigation's `withNavigation()`. In the example above, `FilterSeparator` has no props, and `FilterItem`'s props are both strings. In both instances, a shallowCompare would have the same effect as a normal comparison, making the need for a PureComponent unnecessary. The `keyExtractor` should also try and utilize a unique identifier for the item (i.e. item.id) instead of index, as this could cause unexpected behavior if the order of the items changes.

**Comment by pcooney10** [comment]
@brunolemos have you given this a look? https://github.com/Flipkart/recyclerlistview

**Comment by mayconmesquita** [comment]
@brunolemos @pcooney10
i use https://github.com/Flipkart/recyclerlistview, the perfomance is so great!

**Comment by jsp3536** [comment]
I noticed on iPhone 6s and Samsung Galaxy S8 (using Android 8) scrolling with flatlist is very smooth, but I tried two phones using Android 9 (Samsung Galaxy S10, Essential Phone) and scrolling was very choppy. I switched over to RecycleListView and now all phones scroll very smooth without jank.

**Comment by brunolemos** [comment]
@jsp3536 you talking about the web versions running on these devices browsers, right?

**Comment by jsp3536** [comment]
Yes. I am happy with the performance of RecycleListView but I need to checkout react-window

**Comment by francescoagati** [comment]
@brunolemos have you try with bounces false scrollEventThrottle 300 maxRenderToBatch 1 and updateCellsBatchingPeriod 100 and removeClippedSuvViews true (i dont know if this is implemented in web)

**Comment by RichardLindhout** [comment]
What I found is that every time there are extra items loaded the flatlist will re render the whole list. Even if you use purecomponent. I now use a normal scrollview on the web and the performance is much, much better!

**Comment by francescoagati** [comment]
> What I found is that every time there are extra items loaded the flatlist will re render the whole list. Even if you use purecomponent. I now use a normal scrollview on the web and the performance is much, much better!

do you use keys?

**Comment by francescoagati** [comment]
and keys extractor?

**Comment by RichardLindhout** [comment]
@francescoagati Yes, you should try to make a flatlist and log the render function of the item with the index you will see that it will log every time extra items are added, instead of only the newly rendered ones

**Comment by necolas** [comment]
FlatList wasn't built to support the web, where the solution would probably have to involve juggling a bunch of web APIs to try to find extra performance from somewhere. I don't think supporting the web is a priority at the moment (cc @sahrens), but FB might eventually have a cross-platform solution and Google is working on a built-in virtualizer that might be something we can use one day.

**Comment by brunolemos** [comment]
I am not sure the problem is with FlatList.

I replaced it with `react-window`'s `FixedSizeList` and I had the same result: https://github.com/devhubapp/devhub/issues/155

Need someone with this same problem to also try react-window or react-virtualized to see if it will work well on their project.

**Comment by brunolemos** [comment]
Closing since I don’t have these issues anymore and they might have been mostly because the renders were a bit expensive.

I’ve rewritten my list item components to be simpler. For example, their height are now pre-calculated (this is important) and they don’t do any computation inside the render. Also removed the deep nested custom components, it’s now a single ItemComponent as flat as possible. 

Things are fast now. 

I did switch to react-window on web, it is faster but not a huge deal.

**Comment by nihp** [comment]
@brunolemos Any documentation related to disableVirtualisation for web, android and iOS

**Comment by RichardLindhout** [comment]
Just use a normal scrollview instead of a flatlist in the web @nihp.

**Comment by nihp** [comment]
I am using iOS, here I need to know about the **disableVirtualisation**. I am using SrcollView and Flatlist in my app. 

Need to smoothen the scroll in iOS so I asked about **disableVirtualisation**

**Comment by RichardLindhout** [comment]
There is no virtualization in the flatlist of react-native-web.

**Comment by RichardLindhout** [comment]
I'm wrong I think, it is available in the DevHub source: https://github.com/devhubapp/devhub/blob/f08c991f9d9ca324c23ebbf92e7a6a1de8428e22/packages/components/src/components/cards/NotificationCards.tsx#L339

**Comment by nandorojo** [comment]
I solved this in my app by remaking `renderItem` component from scratch. It went from terrible, glitchy performance to butter. I was originally passing entire data objects to each list item. Then, in each component, I was checking my SWR cache to get more data about them.

For context, I was displaying an infinite scroll search list of artists (think Netflix search.) I wanted to show users if they've liked the artist before or not, etc. I was originally grabbing this data from _within_ each component, since it was in my global cache.

I changed this by turning each card into a fully "dumb" component, with very little code. It only receives primitive props (`hasLiked`, `starRating`) and memoized functions (`onPress(id: string)`). This has helped dramatically.

Oddly, adding `getItemLayout` caused it to flicker a lot on native. This is pretty surprising, given that I am using deterministic heights.

I highly recommend making your list item nimble. Don't pass the entire list object down to it – only the data it needs. Keep any functions at the top level of the list component, and memoize them before passing them down to each item. And, as people have mentioned here, memoize each list item if they re-render too often and you're seeing issues.

In case it's useful, these are the props I ended up with. I memoized every function I passed to `FlatList` (this might be overkill, but it worked for me.)

```jsx
<FlatList
  data={hits}
  removeClippedSubviews={Platform.OS !== 'web'}
  renderItem={renderItemFast} 
  ListEmptyComponent={ListEmptyComponent} // memoized function
  numColumns={itemsPerRow}
  // force re-render when items per row changes, since this can't be changed on the fly
  key={`list-${itemsPerRow}`} 
  initialNumToRender={10}
  keyExtractor={keyExtractor}
  onEndReached={fetchMore}
  keyboardDismissMode="on-drag"
  keyboardShouldPersistTaps="handled"
  style={style.container} 
/>
```

**Comment by viniciushernandes** [comment]
Only add `disableVirtualization` and worked for me.

**Comment by louicoder** [comment]
> Only add `disableVirtualization` and it worked for me.

This works like a charm. I'm curious to know where there's a deprecated label on it. I have tried to optimize my Flatlists in all ways but I would always get a warning Of Flatlist not optimized. This looks like the best option for now.

Also for those curious, there's another package called [recyclerlistview](https://github.com/Flipkart/recyclerlistview) which offers native performance

**Comment by JalalMitali** [comment]
@louicoder @viniciushernandes @brunolemos any better solution than `disableVirtualization` ? thanks in advance!

**Comment by arys** [comment]
increasing windowSize fixed it for me
`windowSize={40}`
