### ISSUE TITLE
visited styles

### ISSUE THREAD

**Issue by EvanBacon** [necolas/react-native-web#1347]
**Is your feature request related to a problem? Please describe.**

I cannot seem to figure out if anchor pseudo classes like `:visited` or `:active` are supported in React Native for web. I can somewhat emulate the active state with `onPressIn` but if there is no way to reset the default visited style with RNW, it'd be nice to have it documented somewhere.

**Describe a solution you'd like**

Perhaps a `visitedStyle` or a `visted` style prop that can consume another style object. 

**Describe alternatives you've considered**

Just documenting that this should be done in CSS.

**Comment by necolas** [comment]
Pseudo-classes aren't supported. Is this because you're using React DOM and `<a>` in your code? I saw that in one of your repos. Even in that case setting a color will override the native visited color.

But you should use `Text` to create links as explained [here](https://github.com/necolas/react-native-web/blob/master/docs/guides/web-recipes.md)

```
<Text accessibilityRole="link" href="https://google.com" />
```

Pressed state is done the same way as you would do it in React Native. We'll have something more convenient in the future that can replace all the Touchables too.
