### ISSUE TITLE
Dimensions change doesn't work reliably on iOS mobile safari 

### ISSUE THREAD

**Issue by brunolemos** [necolas/react-native-web#1369]
**The problem**
Sometimes I get wrong dimensions or the event simply don't fire.

**How to reproduce**

Simplified test case: https://necolas.github.io/react-native-web/examples/

Steps to reproduce:
1. Open on iOS safari on a real device: https://necolas.github.io/react-native-web/examples/
2. Pinch to zoom sometimes
3. See the value updates sometimes, and easily gets wrong

**Expected behavior**
Work reliably even with pinch to zoom

**Environment**

* React Native for Web (version): Latest
* React (version): Latest
* Browser: iOS mobile safari

**Comment by brunolemos** [comment]
Seems to be a bug with iOS Safari. And Apple's workaround is an interval to get the new window size every 500ms: https://hackernoon.com/onresize-event-broken-in-mobile-safari-d8469027bf4d

I'll close because this might be a thing for user land. Opened so you are aware of this.

**Comment by EvanBacon** [comment]
> And Apple's workaround is an interval to get the new `window.innerWidth` every 500ms

God have mercy

**Comment by Freddy03h** [comment]
Hi @brunolemos ! I'm working on a related issue #1905 and I want your insight about the browser expected behavior.

pinch-to-zoom doesn't trigger a `resize` event on mobile (ios safari & android chrome), we can see `window.innerWidth` will be updated on safari (after a reload or an orientation change) but it doesn't change on chrome.

It seem that it's a [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=174362) on safari and `innerWidth` _shouldn't change under pinch zoom_

For the issue I work on, I used `documentElement.clientWidth` instead of `window.innerWidth` ([demo here](https://codesandbox.io/s/rnw-dimension-documentelement-clientwidth-03o0c?file=/src/App.js)) and it seem to have a correct behavior about pinch to zoom (it doesn't change), do you think it can solve this issue too? Thanks.

**Comment by necolas** [comment]
Closing this in favor of #1369
