### ISSUE TITLE
Triggering click on Touchable via testing library not triggering onPress

### ISSUE THREAD

**Issue by nealoke** [necolas/react-native-web#1422]
**The problem**
When using `react-testing-library` for testing components made with `react-native-web`, I'm unable to trigger the `onPress` handler with `fireEvent.click(node)`. Currently I have to add 2 `fireEvent` like shown below. To me this feels wrong as it also triggers on click.

```
fireEvent.touchStart(getByTestId("thumbnail-1"));
fireEvent.touchEnd(getByTestId("thumbnail-1"));
```

**How to reproduce**
https://codesandbox.io/s/issue-react-native-for-web-4vtvw?fontsize=14

Steps to reproduce:
1. Open sandbox
2. Run test
3. See that the one for `click` fails while the one wiht `touch` works

**Expected behavior**
Should work the same for `click` as for `touch`, aka both tests should pass.

**Comment by necolas** [comment]
The responder system doesn't rely on `click` events so you can't expect to dispatch those DOM events have have `onPress` get called.

**Comment by nealoke** [comment]
@necolas on what do they rely then? And why does clicking it in a browser work?

**Comment by necolas** [comment]
Mouse, touch, and eventually pointer events. `react-testing-library` isn't really the right tool for the job. Browsers dispatch a whole sequence of events ([example](https://github.com/facebook/react/blob/56d1b0f/packages/react-events/src/dom/testing-library/domEventSequences.js#L74)) and unless you want to fire that entire sequence in your tests, you won't be able to reproduce the expected behavior.

`react-native-testing-library` does a better job because it doesn't try to emulate the native events, but instead calls the high-level callback directly on a shallowly rendered element. This means you don't have to test the integration between the framework and the platform (not your responsibility), and instead test just that your logic/response is correct when a high-level callback like `onPress` is called with a certain event.

**Comment by nealoke** [comment]
Thanks for the explanation, very interesting. Do you have an example of tests written this way?

**Comment by necolas** [comment]
https://github.com/testing-library/native-testing-library
https://github.com/callstack/react-native-testing-library

**Comment by aaronmgdr** [comment]
ah this was informative, thanks
