### ISSUE TITLE
[Proposal][Remove] create-react-class is no longer used by RN

### ISSUE THREAD

**Issue by ecreeth** [necolas/react-native-web#1531]
**Is your feature request related to a problem? Please describe.**
As mentioned in PR [#27861](https://github.com/facebook/react-native/pull/27861), RN is no longer using create-react-class

**Describe a solution you'd like**
I propose that we eliminate the use of `create-react-class`

**Comment by necolas** [comment]
That will happen when I port the latest changes over

**Comment by brunolemos** [comment]
It seems only `ScrollView` is left, probably because of the `ScrollResponder.Mixin`:

https://github.com/necolas/react-native-web/search?q=%22create-react-class%22&unscoped_q=%22create-react-class%22

https://github.com/necolas/react-native-web/blob/cfe36d780e981885ce73862a9effcea29e7ea1c9/packages/react-native-web/src/exports/ScrollView/index.js#L13
