### ISSUE TITLE
FlatList - onEndReached not triggered when new items added and content height shorter than visible height

### ISSUE THREAD

**Issue by yairopro** [necolas/react-native-web#1608]
When content size change, `_maybeCallOnEndReached` is called.  Nice !

👇🏻But because of this check in the condition inside the `_maybeCallOnEndReached`
https://github.com/necolas/react-native-web/blob/5287044f403d881a13e17f140c5575ce0661587f/packages/react-native-web/src/vendor/react-native/VirtualizedList/index.js#L1290
then adding new items won't trigger the `onEndReached` callback, and thus even though the content height is shorter than the layout height.

[Here's a snack](https://snack.expo.io/HBEUwZIRR).
Can't say why but on mobile the state is updated before `_maybeCallOnEndReached` is called.

![Screen-Recording-2020-05-05-at-14 52 43](https://user-images.githubusercontent.com/8110568/81063630-df655500-8ee0-11ea-947e-8b2ce790ed9e.gif)

**Comment by necolas** [comment]
I just copy paste FlatList from RN. I don't think it's a good idea to use it on web. Choose a cross platform list package instead

**Comment by yairopro** [comment]
> I don't think it's a good idea to use **it** on web

You mean this feature, or the FLatList itself ?

**Comment by wayne-tt** [comment]
Whenever onLayout event occurs, _maybeCallOnEndReached is called.

I am also struggling with this bug.

**Comment by DavidRieman** [comment]
> I just copy paste FlatList from RN

@necolas is it possible that the RNW copied version of FlatList (or VirtualizedList or whatnot) is simply out of date with RN FlatList's bugfixes?  We're also seeing what appears to be [web-only bugs](https://stackoverflow.com/questions/71152486/how-to-virtualize-a-flatlist-inside-flatlist-rn-web) on what has otherwise been a rock-solid, cross-platform component.

(RecyclerListView has other major issues even in their basic "how to" sample, and IDK what else to try now.  Did anyone else here ever find a cross-platform list package that works better than FlatList?)

**Comment by Sir-hennihau** [comment]
Any recommendations for a library that works as a drop-in replacement? Or any progress on the problem in the meantime?
