### ISSUE TITLE
Remove CheckBox

### ISSUE THREAD

**Issue by efoken** [necolas/react-native-web#1710]
As written in the README "Components and APIs deprecated in React Native are not supported by React Native for Web.", the CheckBox component should be removed 😄 See: https://reactnative.dev/docs/checkbox.html

React Native CheckBox only supports Android anyways – so one should use `@react-native-community/checkbox` which currently supports iOS and Android.

**Comment by RichardLindhout** [comment]
I think we should add a web implementation to the community package first. + it's not removed it's deprecated.

**Comment by necolas** [comment]
I think it was a mistake to remove checkbox from RN that occurred because FB wasn't maintaining the implementation in RN. But a component like this should be part of a core framework. A lot of the packages moved out of core have been poorly maintained, and this one hasn't added Web implementation for years. So I'll be keeping the API here
