### ISSUE TITLE
createStyleResolver to allow custom STYLE_ELEMENT_ID as param

### ISSUE THREAD

**Issue by ivgam** [necolas/react-native-web#1763]
**Is your feature request related to a problem? Please describe.**

While playing around with the library I found that if 2 applications exist in the same page and both are using react-native-web, the CSS generated by `createStyleResolver` of the second application overwrites the CSS element generated by the first.

**Describe a solution you'd like**

Looking at the code present on https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/createStyleResolver.js#L28-L34 if the function received an optional param that could choose the id of the style element, collisions like the one explained above could be prevented and multiple applications could be running on the same page.

**Describe alternatives you've considered**

**Additional context**

**Comment by riteshoyo** [comment]
@necolas Can you please look at this request? This issue is being faced by multiple people.

**Comment by necolas** [comment]
Both applications will share the same stylesheet unless they are bundling 2 different versions of the stylesheet.

**Comment by jbeuckm** [comment]
We are trying to move our reusable components to a RNW component library. When a component from the new library is loaded into the app, the global css gets overridden. I don't know why the css RNW adds should be different since the component library is in a monorepo with the app and uses the same react/react-dom/react-native-web dependencies. I would prefer a way to ignore the RNW global styles in the library and only bring in css from library components.
