### ISSUE TITLE
Escape key will close all modals

### ISSUE THREAD

**Issue by endygower** [necolas/react-native-web#1817]
**The problem**
Pressing escape key will close all modals when `animationType !== 'none'`

**How to reproduce**
https://codesandbox.io/s/red-snowflake-qcstb

Steps to reproduce:
1. click open modal 
2. click open modal in modal 1
3. click open modal in modal 2
4. press escape

**Expected behavior**
Pressing escape should only close the top most modal like `animationType === 'none'`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.8
* React (version): 16.13.1
* Browser: chrome 86

**Comment by RichardLindhout** [comment]
cc: @imnotjames

**Comment by imnotjames** [comment]
It doesn't close all modals - it closes the lowest modal (with depth `1`) - and the rest get closed because they're mounted within the modal you're displaying.  The event gets stopped in that modal.

In the non-animated case, the same thing happens - except it goes with the last created (depth `2` or more) and then stops the propagation so it works as we'd like.

I'm not sure how to best approach this without adding a global state of the "stack" of visible modals somewhere.  I had that implementation before but removed it to attempt a simplification.

**Comment by endygower** [comment]
I did some experiment on why this happened, it has to do with onAnimatedEvent being propagated to the lowest modal (depth 1) when closing depth 2 or more because it is a descendant of ModalAnimation. Please check the console on this sandbox to demonstrate my point https://codesandbox.io/s/modest-rain-z47nl

Because of the propagation, modal 1 is told to be closed.

I think we can stop the event to only target the caller div. What do you think?

**Comment by imnotjames** [comment]
Oh, dang, you're very right!  Nice catch there.

Though I'm not.. sure why that would be propagating between modals like that - even if they're nested.

Because of the portal that the modals use they don't TECHNICALLY nest in the DOM - maybe react is doing some magic to make sure the events propagate?

Either way, two ways I can thing of to help some with this:

* Call Stop propagation on the event - this SORT OF WORKS - unless if there's a child in the modal which propagates this when we don't expect it!  That could be bad.
* Add a `ref` to the animation `div` and compare the ref on the animation end event to ensure we're looking at the correct ref?
* Check that `event.target === event.currentTarget` - make sure the event was emitted from the same location we're consuming it

That third one would be the easiest - just add a check `if (event.target !== event.currentTarget) return` and blammo, should be good to go.

**Comment by imnotjames** [comment]
Here's a branch with the fix and tests - https://github.com/necolas/react-native-web/compare/master...imnotjames:fix/1817/modal-escape-key-with-animations gonna come back to this in the morning and see if it still feels like the right path forward & open up a PR
