### ISSUE TITLE
PanResponder *ShouldSetResponder not bubbling as expected 

### ISSUE THREAD

**Issue by staffan-klashed** [necolas/react-native-web#1825]
**The problem**
The React Native [documentation](https://reactnative.dev/docs/gesture-responder-system) says: _onStartShouldSetResponder and onMoveShouldSetResponder are called with a bubbling pattern, where the deepest node is called first._ 
Unless I’m mistaken this is not the case for onMove* in RNW, as illustrated by this sandbox where onStart* seems to bubble correctly but onMove* seems to capture the event on the way down.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/mystifying-flower-3bbcy?file=/src/App.js

The small gold colored view is a draggable child of the also draggable red view. In the first case, where no onMoveShouldSetResponder handler is provided to either parent or child, it works as expected. In the second case however, the parent appears to steal the gesture from its child. 

**Expected behavior**
The small gold colored square should be draggable independently from its red parent in both cases. 

**Environment (include versions). Did this work in previous versions?**
No, not that I'm aware of.

* React Native for Web (version): 0.14.8
* React (version): 16.13.1
* Browser: Chrome 86.0.4240.198

**Additional context**
I can work around this by returning false in onPanResponderTerminationRequest for both parent and child, but that has other implications.

**Comment by necolas** [comment]
The behavior you're seeing looks correct to me (i.e., as designed), and matches that of the native platforms. This is what is happening:

1. A start event grants the responder to the gold view.
2. A move event happens.
3. The responder system looks up the tree from the responder (i.e., skips the responder) and finds a parent that wants to become the responder for a move.
4. The parent becomes the responder.

You can see this if you add logging around `onPanResponderGrant` on each gesture handler.

If you had even more ancestors that all set `onMoveShouldSetPanResponder` to `true`, then each move event would move the active responder one element up the tree until you reached the top-most ancestor. Unless you called `e.stopPropagation` in the `shouldSet` handler.

If you don't want the first parent of the gold view to become the responder following a move over the gold view, you can either use some logic in the `onMoveShouldSetPanResponder` handler to first determine if the target of the move is the parent itself rather than the gold view, or reject the termination request on the child under specific conditions.

**Comment by staffan-klashed** [comment]
Thank you, very informative and apologies for posting as a bug. I didn't realize the responder system intentionally only looks up the tree when there is a responder already.

**Comment by necolas** [comment]
it took me a moment to realise what was going on too :)
