### ISSUE TITLE
Complete sample app (F8 app?)

### ISSUE THREAD

**Issue by vonwao** [necolas/react-native-web#196]
It would be really interesting to see a complete app that works in mobile and on the web too.  If F8 app could be done, maybe a subset of it, it would be a great demo.  

That would open possibilities for a lot of small startups who can't afford to develop a mobile app and web app at the same time.  Any thoughts?  I would like to try but don't think I will have the time right now.

**Comment by necolas** [comment]
I don't have the time either. I'm more interested in using this in production apps and internal tools because we can use our infra to answer more questions. If someone in the OSS community wants to build a multi-platform app that would be cool. I've been talking to RN UI library authors to get web support build into those too.

Going to close as this isn't an issue with the library or something we're going to act upon at the moment. Thanks
