### ISSUE TITLE
Calling I18nManager.forceRTL(true) flips text align left/right

### ISSUE THREAD

**Issue by goldylucks** [necolas/react-native-web#1978]
**The problem**
I18nManager.forceRTL(true) flipps textAlign right->left and vice versa. That doesn't happen on react native.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/amazing-maxwell-idkej?file=/src/App.js

Steps to reproduce:
1. Notice the text is on the left side even tho textAlign is set to 'right'

**Expected behavior**
calling forceRTL should NOT flip right/left text align values. See example in expo:
![image](https://user-images.githubusercontent.com/6963212/114012041-87f90300-986e-11eb-9320-3530ff49c384.png)

**Environment (include versions). Did this work in previous versions?**
I don't know if it worked in previous versions

* React Native for Web (version): 0.15.6
* React (version): 16.13.1
* Browser: chrome

**Comment by necolas** [comment]
This looks correct to me. The expo snack doesn't seem to do anything at all when you force RTL; it won't even flip the `start/end` properties. If you want to prevent left/right flipping you have to call `I18nManager.swapLeftAndRightInRTL(false)`. I think RN wants to make this the default one day but I don't think it has been done yet. Unfortunately, RN has not documented the `I18nManager` so you probably wouldn't have realized this. But there are web docs here https://necolas.github.io/react-native-web/docs/i18n-manager/

**Comment by goldylucks** [comment]
Thanks for the response.
But this behavior of `react-native-web` isn't consistent with `react-native`. Shouldn't it be consistent?

Otherwise we have to add checks for `Platform.OS === 'web'` everywhere that we use left/right styling properties

**Comment by necolas** [comment]
RTL features of RN aren't working at all in the Expo Snack. The implementation in RNWeb is correct as far as I know and can tell about the current state of the I18nManager in RN, which is otherwise undocumented.

**Comment by goldylucks** [comment]
I didn't know that about expo snack, but anyways the reason I opened this bug is because on our app the forceRTL isn't consistent between RN and RNW, so as a workaround we added a conditional anywhere there's a left/right styling.

**Comment by necolas** [comment]
> I didn't know that about expo snack

I said the same thing in my first comment.

> on our app the forceRTL isn't consistent between RN and RNW

As I said, If you want to prevent left/right flipping you have to call `I18nManager.swapLeftAndRightInRTL(false)`.

There has been no documented change to RN since this was implemented, and no one I've mentioned this issue to on the RN team seems to know either. It's possible the left/right swapping by default was changed, but I don't know yet. It's also possible this is a configuration issue on your end, since the native RTL handling is not as good and needs app restarts and possibly some native side configuration too. Hard to know since all this is undocumented in RN
