### ISSUE TITLE
Hitting enter with focused Text component does not invoke onPress

### ISSUE THREAD

**Issue by jondkoon** [necolas/react-native-web#2094]
**The problem**
- Focusing a `Text` component and hitting `[enter]` no longer invokes `onPress`
- Looks like a regression introduced with 2a930b7e3f7f58638e457e1f15b608c6f6c010e8

**How to reproduce**
Simplified test case: https://codesandbox.io/s/wonderful-dawn-fdity?file=/src/App.js

Steps to reproduce:
1. Focus the Text component and hit enter
2. Observe that the alert does not appear
3. Downgrade RNW to `0.16.5` and observe that hitting enter does display the alert

**Comment by necolas** [comment]
Going to close this because latest RNW "works" https://codesandbox.io/s/jovial-buck-1ez2og?file=/src/App.js

RNW now renders a `button` element if you use a `button` role, so you get the native click/keyboard handling. Text.onPress still isn't called for keyboard if the element 'role' doesn't correspond to an element that natively handles Enter -> click on web. That's not quite how RN works, but on web we can think of onPress as behaving like native onClick. 

I could add a patch so onKeyDown is used to call onPress in all cases, but that would add complexity back and discourage people from using roles like `button` and `link` for keyboard support. I'm assume the current state is acceptable but let me know if not. These days we're also trying to implement web compat on RN.
