### ISSUE TITLE
Scroll does not work for TextInput nested in inverted FlatList

### ISSUE THREAD

**Issue by roryabraham** [necolas/react-native-web#2435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

If you have a TextInput nested inside a nested FlatList, then the TextInput is not scrollable.

### Expected behavior

Just as it behaves inside ScrollView or non-inverted FlatList, nested TextInputs should be scrollable.

### Steps to reproduce

1. Open the provided code sandbox reproduction example
1. Scroll through the list
1. Attempt to scroll the TextInput that's in the middle of the FlatList

### Test case

https://codesandbox.io/s/rnw-nestedtextinputscroll-xhuvrf?file=/src/App.js

### Additional comments

This bug was introduced [here](https://github.com/necolas/react-native-web/commit/7ec2489c78f9734bae5bcfdc514b0c91621a6300), and it's happening because the `invertedWheelEventHandler` is handling the event before the (global?) parent handler.

**Comment by roryabraham** [comment]
I put together a [PR](https://github.com/necolas/react-native-web/pull/2436) to fix this issue.

**Comment by necolas** [comment]
Sorry but I'm not accepting any more PRs for VirtualizedList because we're going to be publishing it out of the React Native monorepo as a package that React Native for Web takes on as a dependency. See https://github.com/facebook/react-native/issues/35263 for more details. We'll have to think about how to address these issues there.
