### ISSUE TITLE
TextInput: reimplement autogrow

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#287]
Remove the dependency on `react-textarea-autosize` and ape the implementation in [Polymer](https://github.com/PolymerElements/iron-autogrow-textarea/blob/master/iron-autogrow-textarea.html) or [Material UI](https://github.com/callemall/material-ui/blob/master/src/TextField/EnhancedTextarea.js)

**Comment by necolas** [comment]
@paularmstrong has offered to take this on

**Comment by necolas** [comment]
https://github.com/paularmstrong/react-native-web/tree/paularmstrong/textarea-autosize

**Comment by paularmstrong** [comment]
Just need to find some more time to finish things up. I'll work on adding/using `minNumberOfLines` and `maxNumberOfLines` as we discussed in chat. Also still need to fix things to not remove margins.

There's still an alternative solution that avoids adding all the extra markup and instead adds a mirror `textarea`. The only issue there is that we have to read all of the computed style values on every keyPress event and calculate the height manually. I'm avoiding that solution because it doesn't seem very maintainable and also has some performance impacts. (this is how react-textarea-autosize works)

**Comment by necolas** [comment]
I'm going to remove the existing dependency for now

**Comment by natew** [comment]
Just a heads up actually this is broken in the demos. Autoexpanding text input doesn't expand for me on Chrome 57

**Comment by necolas** [comment]
Yeah the demos haven't been updated in a while…but it will still be broken as we haven't implemented the events RN emits. It's quite hard to do that given how `textarea` works in browsers

**Comment by natew** [comment]
Oh didn't realize it was using textarea! We need a clean room implementation or something

**Comment by necolas** [comment]
Going to close this as autogrow isn't baked into React Native and the mechanism by which autogrowing `TextInput` is currently implemented in user space is with event data. Not sure what the best way forward is

**Comment by rxb** [comment]
In case anyone comes across this issue looking for auto-expanding, here's a snippet to add to your TextInput:

```
onChange={(event) => {
	this.setState({height: event.nativeEvent.srcElement.scrollHeight});
}}
```

Then set minHeight style to this.state.height.

**Comment by petrbela** [comment]
Perhaps this should be reopened and implemented (possibly using @rxb's solution although it doesn't seem to handle shrinking) since TextInput autogrow functionality has been part of RN since [at least 0.60](https://github.com/facebook/react-native/commit/dabb78b1278d922e18b2a84059460689da12578b)
> nowadays `<TextInput>` component is always autoexpandable (on both iOS and Android)

**Comment by Sharcoux** [comment]
The follow up is in #795
