### ISSUE TITLE
Why all examples import components from 'react-native' instead of 'react-native-web'? Is it a typo or I got something wrong?

### ISSUE THREAD

**Issue by shweta-code** [necolas/react-native-web#424]
For example from 'Image' component

import { Image, PropTypes, StyleSheet } from 'react-native'

**Comment by RangerMauve** [comment]
The idea is that you write code importing from React-Native (so that it will run on Android / iOS), but when you're building your app for the browser, you alias the `react-native` module to instead point at the `react-native-web` module.

You can see the webpack config which enables that [here](https://github.com/necolas/react-native-web/blob/master/examples/.storybook/webpack.config.js#L30)
