### ISSUE TITLE
`flex` gets converted to `flex-grow`

### ISSUE THREAD

**Issue by dsernst** [necolas/react-native-web#426]
**What is the current behavior?**

When I use `flex: 3` in a component's `style` prop, it gets converted to `flex-grow: 3` in the DOM.

**What is the expected behaviour?**

`flex: 3` in react-native-web should appear as `flex: 3` in the DOM, not `flex-grow`.

**Environment (include versions)**

React Native for Web (version): `^0.0.81`

**Comment by necolas** [comment]
They are equivalent

**Comment by dsernst** [comment]
Appreciate the quick response. Are you sure they are equivalent? When I use `flex` in the DOM, it implicitly adds a `flex-shrink` and `flex-basis` as well:

<img src="https://cloud.githubusercontent.com/assets/6340841/25036193/2a0166d6-20a7-11e7-9cd8-379b751b4a66.png" width=168 />

I had to manually add a `flex-basis` to `react-native-web` components to get the same layout in `js-to-css` vs traditional css.

**Comment by necolas** [comment]
React Native's `flex` is a bit different. It also adds `flex-shrink:1`, but uses `flex-basis:auto` instead of `flex-basis:0%`

**Comment by maszaa** [comment]
I tried the calculator done in [Kyle Bank's tutorial](https://kylewbanks.com/blog/react-native-tutorial-part-1-hello-react) ([code](https://github.com/KyleBanks/ReactCalculator)). Works fine otherwise but the flex is converted to flex-grow which causes the InputButton components to align ugly:
![flex-broken](https://user-images.githubusercontent.com/17689044/26939625-8e3c16fa-4c80-11e7-897a-a02d2526b86f.png)

Changing the CSS rule (manually on the browser dev tools) to `{flex: 1}` fixes the problem:
![flex-fix](https://user-images.githubusercontent.com/17689044/26939671-b2499ac2-4c80-11e7-8fb2-88433f71744c.png)

Could this convertion be fixed?

**Comment by necolas** [comment]
As you can see in the screenshot, the only difference is the value of `flex-basis`

**Comment by maszaa** [comment]
But whhy is the `flex` converted (only) to the `flex-grow`? They aren't the same thing. ["Flex and flex-grow, flex-shrink, and the flex-basis combined together would be."](https://www.w3schools.com/cssref/css3_pr_flex.asp)

**Comment by RangerMauve** [comment]
@maszaa This library is simply following the [react-native API for flexbox](https://facebook.github.io/react-native/docs/layout-props.html#flex)

To quote their docs:

> In React Native flex does not work the same way that it does in CSS. flex is a number rather than a string, and it works according to the Yoga library at https://github.com/facebook/yoga
>
> When flex is a positive number, it makes the component flexible and it will be sized proportional to its flex value. So a component with flex set to 2 will take twice the space as a component with flex set to 1.
>
> When flex is 0, the component is sized according to width and height and it is inflexible.
>
> When flex is -1, the component is normally sized according width and height. However, if there's not enough space, the component will shrink to its minWidth and minHeight.
>
> flexGrow, flexShrink, and flexBasis work the same as in CSS.

**Comment by maszaa** [comment]
But doesn't

> When flex is a positive number, it makes the component flexible and it will be sized proportional to its flex value. So a component with flex set to 2 will take twice the space as a component with flex set to 1.

actually mean the same thing as

> [The flex property specifies the length of the item, relative to the rest of the flexible items inside the same container.](https://www.w3schools.com/cssref/css3_pr_flex.asp)

?

React Native has `flexGrow` which works the same way as `flex-grow` in CSS so converting its `flex` to CSS' `flex-grow` seems strange as `flex` in React Native isn't `flexGrow`.

**Comment by necolas** [comment]
> But why is the flex converted (only) to the flex-grow?

`flex` is converted to `flexGrow`, `flexShrink`, and `flexBasis`.

https://github.com/necolas/react-native-web/blob/cdf13b880d44a045d6a45be34e23561109672df2/src/apis/StyleSheet/createReactDOMStyle.js#L155-L160

**Comment by maszaa** [comment]
My bad. What about setting that to 0? At least worked for the calculator when I manually set all the flex components to have `flexBasis: 0`

**Comment by necolas** [comment]
Looks like maybe we should do that. I'll investigate a bit more

**Comment by sonaye** [comment]
`flexBasis: 0` should be added to match the behavior of react native.

**Comment by maszaa** [comment]
Thanks for the fix! Unfortunately my `flex` attributes still convert to `flex: value, flexGrow: 1, flexBasis: auto`, though the code now has `resolvedStyle.flexBasis = '0%';`. I've installed the latest version, re-installed all npm packages and cleaned the whole project but that didn't help. Where could the problem be?

**Comment by nthtran** [comment]
The problem is even though `resolvedStyle.flexBasis = '0%';`, `flexBasis`  is `auto` [in the default View style](https://github.com/necolas/react-native-web/blob/master/src/components/View/index.js#L93). So when it [loops through all the style props](https://github.com/necolas/react-native-web/blob/master/src/apis/StyleSheet/createReactDOMStyle.js#L140), when `prop` is `flex`, `resolvedStyle.flexBasis` is set to `0%` correctly. When `prop` is `flexBasis`, `resolvedStyle.flexBasis` [is set back to `auto` ](https://github.com/necolas/react-native-web/blob/master/src/apis/StyleSheet/createReactDOMStyle.js#L214).

**Comment by ThaJay** [comment]
In react-native-electron I had a bug that a text element would take up full height in production but in development it would only be the height of the text like it shoud. Thanks to this discussion, I was able to solve it with:
```
style = {
  flex      : 0,
  flexGrow  : 0,
  flexBasis : 0,
  flexShrink: 1,
}
```
