### ISSUE TITLE
TextInput: add 'blur', 'clear', and 'focus' instance methods

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#53]
Parity with RN. Add to docs too.

**Comment by necolas** [comment]
Fixed by 949cb758944b7c5074ccb4a5e537c2982da86963

**Comment by ThaJay** [comment]
There is no `focus()` on `TouchableOpacity`, in react-native but in the DOM there is.
I don't know if this is not in react-native-web on purpose or not, because these docs https://github.com/necolas/react-native-web/blob/master/website/guides/direct-manipulation.md do not include specific components.
