### ISSUE TITLE
Next steps: react-web and react-primitives

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#531]
cc @yuanyan (Taobao) @lelandrichardson (Airbnb) @peggyrayzis (MLS)

Starting a discussion about some possible next steps to support the growing interest in `react-native-web`/`react-primitives` from companies and library authors. These are my current thoughts:

1. `react-native-web` package is renamed `react-web` before 0.1.0 release.

We have `react-native`, `react-macos`, `react-desktop`, etc. Naming the web equivalent `react-web` seems like a clear choice. But that package name is already taken; @yuanyan is Taobao open to transferring the package name and/or migrating to `react-native-web`? What do you need for that to happen? If not, should we scope this package (e.g., `@reactjs/react-web`), rename it to something else, or leave it as is?

2. `react-native` compatibility layer is exported from `react-web/native`.

Web needs its own components. And several React Native components and prop names are either specific to a single native platform or too native focused. I'd like to publish the web-specific API by default (excluding shims for `NativeModules`, `StatusBar, etc.`) and a more complete `react-native` compatibility layer at `react-web/native` that could be used to safely render components built with the React Native API (e.g., you're porting an existing RN app or using RN OSS components).

3. Other libraries

Not everyone can use haste or tree-shaking in their app. To better support `react-primitives` and component libraries in particular, Leland suggested a Babel plugin could rewrite the imports to reach into the package internals (I could include a module map for the plugin to use or export the plugin from this package `react-(native-)web/babel`).

Let me know your thoughts, thanks

**Comment by peggyrayzis** [comment]
🙋 Happy to help! We haven't officially announced this yet since we're still working out some minor post-release bugs but last week, we launched [our first site](https://matchcenter.mlssoccer.com/schedule) w/ RNW into prod. Everything on the schedule page is built with universal components + several RN libs (`react-native-calendars`, `react-native-svg`, `victory-native`, `react-native-vector-icons`) & we're super happy w/ the outcome.

I'm all for whatever is going to ease adoption & push universal components forward, even if it means breaking changes to our application in the short-term. Here are my initial thoughts:

1. Doesn't matter to me what it's called but `react-web` sounds reasonable :)

2. Is `react-web` going to look more like the web primitives of `react primitives` & `react-web/native` will be everything else that doesn't fit? Where do you put something like PanResponder, which is more native focused but also needs web specific logic to support mouse events? Can you talk a little more about what this compat layer will look like?

3. I love the idea of a babel plugin to rewrite the imports! 😍 Right now, the process to use RN libs on the web feels pretty hacky with all of the aliasing. Anything we can do to standardize the process, especially as we divide RNW components & APIs into web/native packages, would be really helpful for newcomers.

Have you thought about what the docs would look like for the v0.1.0 release? The getting started guide is a good start, but we should think about user guides beyond getting started for solutions like using RN component libs on the web, recommended cross platform solutions for SVG, SSR, tips for building a universal component library, etc? I'm down to help w/ making this experience better in a couple weeks when my schedule isn't so crazy.

cc @kkemple

**Comment by necolas** [comment]
> Is react-web going to look more like the web primitives of react primitives & react-web/native will be everything else that doesn't fit?

React Web / React Native Web would include web-specific components (e.g., `createDOMElement`, `Checkbox`, `ProgressBar`) while excluding React Native stubs like `StatusBar`. If you need web-specific APIs you import them from `react-(native-)web` rather than an aliased `react-native` module.

The native compat layer would exclude web-specific components and include stubs or mappings for all the React Native exports. Basically what this library currently does but more complete and intended to make it easier to run existing RN code on web by aliasing `react-native`.

React Primitives is narrower in scope and won't be affected either way.

**Comment by kkemple** [comment]
I like the idea, it seems to make it easier to integrate with react-primitives and allows for people without need of native apis to avoid dragging that into the bundle.

This also removes the aliasing problem currently faced with working with other environments like storybook and react-sketchapp, which is really nice.

I think my biggest point of confusion is around what `View` and `Text` become since pan responder and such will become separate APIs. I imagine `View` will change and you would use react-primitives if you want cross-platform components with matching APIs?

**Comment by necolas** [comment]
I don't follow. `View` and `Text` aren't changing, neither is `PanResponder` which already works across platforms. All that and more would still be exported.

I think `react-primitives` may become useful for component library developers, but I think the API is too limited for app development, at which point you'd reach for `react-native`/`react-native-web` and may still want to use aliasing.

**Comment by kkemple** [comment]
alright, im re-reading your last comment and i get it now, i wasn't quite following, but essentially it makes the react-native part more pure. And if you want web specific functionality you have to import that yourself. Is that about right?

**Comment by necolas** [comment]
Yeah pretty much. Right now it's a bit weird that you can import things like `createDOMElement` from the aliased `react-native`.

If you need to use `Artboard` you import it directly from `react-sketchapp`. Similarly, I think the guidance could be to import web-specific exports like `createDOMElement`, `ProgressBar`, `Checkbox`, etc. from `react-native-web` when you need them, and not to expect them to hanging off an aliased `react-native` module. To do that would involve exporting a new module that is specifically for `react-native` aliasing, and it would make the interface (at least) more complete for that use case.

**Comment by lelandrichardson** [comment]
Another thing to keep in mind is that the react-native team has said that they plan to make the core library lighter weight, moving a lot of the non-core APIs to separate modules, which might make something like react-web and react-native able to achieve parity in their exports.

**Comment by necolas** [comment]
Yeah that would be ideal

**Comment by necolas** [comment]
I emailed @yuanyan; he doesn't want to rename `react-web and is focused on making `react-web` run on `rax`.

Maybe `react-webapp`?

I'm going to close this for now and see if someone on my team can pick up the Babel plugin task while I get the rest in order.
