### ISSUE TITLE
Touchable: comparison with RN components?

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#55]
How similar to RN does this need to be? What have I overlooked about the decisions behind the RN components? Should the RN components be provided by this package? Is it a problem to introduce Web divergences given that RN already has many Android/iOS-only props and components?

The `Touchable` component API's in RN were the ones I felt least happy about.

1. Not obvious why there needs to be multiple `Touchable` components with such similar APIs. Why don't they all have a `style` prop? Why is `accessibilityLabel` missing from props?
2. Felt confusing that some `Touchable` components accept single vs multiple children.
3. Felt like slightly inconsistent prop names: `activeOpacity` vs `underlayColor`, even though they are both only in effect when "active".
4. Looks like you could use `onPress*` callbacks to achieve the same outcome as `onShowUnderlay` and `onHideUnderlay`.

The implementations themselves are more complex and comprehensive than what's here so far, and the particularities of the native platforms escape me…so I've probably overlooked some key details. But what I did was:

1. Rolled them all into a single `Touchable` component, added `accessibilityLabel` and `style` props.
2. Only accept a single child (I think Web could accept multiple children though, with a modified implementation),
3. `underlayColor` -> `activeUnderlayColor`
4. Didn't include `onShow/HideUnderlay`.

And I assumed that anyone using with RN at this early stage could create comparable aliases from RNW's `Touchable`, for example:

```js
var TouchableWithoutFeedback = (props) => (
  <Touchable {...props} activeUnderlayColor='transparent' activeOpacity={1} style={} />
)

var TouchableOpacity = (props) => (
  <Touchable {...props} activeUnderlayColor='transparent' style={} />
)

var TouchableHighlight = (props) => (
  <Touchable {...props}
    activeUnderlayColor={props.underlayColor}
    onPressIn={(...args) => {props.onPressIn(..args) && props.onShowUnderlay(...args)}}
    onPressOut={(...args) => {props.onPressOut(..args) && props.onHideUnderlay(...args)}}
  />
)
```

cc @vjeux

**Comment by necolas** [comment]
Noticed some of the defaults differ between the RN touchables though. So perhaps it is more about the the UX of the components?

**Comment by vjeux** [comment]
The Touchable wrapper apis are indeed not very coherent and evolved gradually without a big oversight. But, those components are extremely important, I believe that they are the reason why apps developed with React Native **feel** native.

Touch UIs have the notion of a gesture "lock". The best example is if you have a scrollview with elements inside. If you touch down on an element, it's going to highlight and have the lock. But if you move 5 pixels down, then the scrollview is going to take the lock and the element will unhighlight.

Now, if you swipe away to make the scrollview momentum scroll and before it ended you touch down on an element, then it's going to stop the scrollview but NOT highlight the element because the scrollview had the lock and didn't release it. If you don't implement this nuance, then you're going to trigger the action on the element when you just wanted to stop scrolling and have a terrible user experience.

There are also many subtleties like if you are on a scrollview, the highlight will only appear after ~100ms. The reason is that you may want to scroll which would make the ui flicker. But if you are not inside of a scrollview it will show up instantly.

You can also touch down on the element, drag out to unhighlight and then drag back in and it highlights again. There's also a region outside of the element where it's still going to work. to help with "fat fingers".

Anyway, there's a lot of context that we need to document on those, but know that their behavior is very very very important. However, work is needed to make the API of those component coherent and great.

**Comment by necolas** [comment]
Thanks for the important context here. Fortunately most of the existing implementation works on web; I made some minor changes to the touchable code to get things working in 3c4d7655db65c3ffaefda4b81a94dc5a7b33bfa6. There are few more web-specific concerns that I'll get to, initially keyboard interaction and focus styles.

**Comment by dsernst** [comment]
@necolas: Has this issue ever been re-addressed?

> Touch UIs have the notion of a gesture "lock". The best example is if you have a scrollview with elements inside. If you touch down on an element, it's going to highlight and have the lock. But if you move 5 pixels down, then the scrollview is going to take the lock and the element will unhighlight.
>
> Now, if you swipe away to make the scrollview momentum scroll and before it ended you touch down on an element, then it's going to stop the scrollview but NOT highlight the element because the scrollview had the lock and didn't release it. If you don't implement this nuance, then you're going to trigger the action on the element when you just wanted to stop scrolling and have a terrible user experience.

This is a perfect description of the buggy performance I'm seeing right now with a list of `<TouchableOpacity>`.

Do these subtleties still need to be added before it will match the feel of `react-native`?

---

Thanks. Great insights @vjeux
