### ISSUE TITLE
TypeError: _reactNative.Dimensions.addEventListener is not a function

### ISSUE THREAD

**Issue by papuaaaaaaa** [necolas/react-native-web#581]
**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**
TypeError: _reactNative.Dimensions.addEventListener is not a function

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. write Dimensions.addEventListener("change", () => {})

**What is the expected behavior?**
it is possible to call addeventListener according source code
https://github.com/necolas/react-native-web/blob/master/src/apis/Dimensions/index.js#L58

**Environment (include versions). Did this work in previous versions?**

* OS: Mac OSX 10.11.6
* Device: MacBook Pro (Retina, 13-inch, Early 2015)
* Browser: Version 59.0.3071.115 (Official Build) (64-bit)
* React Native for Web (version): 0.0.116
* React (version): 16.0.0-alpha.6

**Comment by necolas** [comment]
This is not enough information to understand your problem, which is why I ask for a demo example. So I'm going to close this issue.

As you can see here, the API works: https://necolas.github.io/react-native-web/storybook/?selectedKind=APIs&selectedStory=Dimensions

As you can see here, React 16 is not yet supported: https://github.com/necolas/react-native-web#quick-start
