### ISSUE TITLE
Animated.View: Invalid style with id `###`. Skipping...

### ISSUE THREAD

**Issue by joncursi** [necolas/react-native-web#617]
In one of the recent versions of RNW, it looks like the style prop of `Animated.View` stopped working. You can supply a regular style object, or an array of objects, it doesn't matter. The style prop will not apply in the DOM.

Example:

```js
import { Animated } from 'react-native-web';

...

<Animated.View
  style={{marginTop: 15}}
>
  {...}
</Animated.View>
```

Error:

![screen shot 2017-08-29 at 12 38 45 pm](https://user-images.githubusercontent.com/4974609/29832707-0af1fde2-8cb7-11e7-9229-d733da2ce08b.png)

**Comment by necolas** [comment]
Please provide the information requested in the issue template

**Comment by joncursi** [comment]
* Bug
* Current behavior described above
* Repro code provided above
* OS: macOS
* Device: MacBook Pro 2017
* Browser: Chrome
* React Native for Web (version): `0.0.120`
* React (version): `15.6.1`

**Comment by necolas** [comment]
Similarly to the other issue you opened, I can't reproduce this

**Comment by benjipott** [comment]
done in next js app use styledcomponent

**Comment by andrestone** [comment]
Reproduced using storybook.

**Comment by kevinrodriguez-io** [comment]
@necolas Curiously enough, I think I can provide steps to repro:

1- You'll need an expo app with next.js, easiest setup is provided by @expo/next-adapter.
2- If you use styled/native or emotion/native, after you refresh styles will be gone and you'll get a lot of those:

![Screen Shot 2021-02-17 at 6 36 59 PM](https://user-images.githubusercontent.com/6248571/108286681-29a58300-714f-11eb-92b7-777971261e4f.png)

Not happening for me in storybook, creact-app, or mobile. Just next.js

**Comment by MoOx** [comment]
This just happened to me without viable reason (after some runtime/build error).
I just stopped next dev server, put `.next` folder the trash, started dev server again, and everything went back to normal.

I think this might be due to some duplicate modules and/or cache issues.

So try to kill next, trash `.next`, run `dev` again.

**Comment by kevinrodriguez-io** [comment]
I fixed it on my local env:

The issue is I didn't have the babel plugin set up on next.js

**Comment by alexmititelu** [comment]
Ran into a similar issue where styles were skipped in my project. It turned out to be because of multiple RNW instances installed one at project level and one as a dependency of a dependent library. 

Not sure if it was because of the versions mismatch (`0.17.7` and `0.17.5`) or just because there wasn't a single source of truth. But because one of the dependencies was redundant I ended up removing it entirely
