### ISSUE TITLE
Update create-react-app to use babel-plugin-react-native-web

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#629]
React Native for Web now exports a Babel plugin that sets up aliasing of the package and excludes any unused modules from builds. We should create a PR for `create-react-app` to rely on this instead of the webpack alias, as builds will be faster and smaller. AFAIK, the Jest package aliasing might also be unnecessary afterwards.

**Comment by ansumanshah** [comment]
We should have something like `babel-plugin-react-native-web` so that `create-react-app` does not have to download the whole package to setup the plugin.

**Comment by ararog** [comment]
Configure the preset described on getting started guide doesn't seem to work, instruct people to create the webpack config in web directory also introduces an error with webpack 3.
I couldn't validate the steps describe on getting started doc, I have to keep the alias and move webpack config to root dir of the project to let webpack compile things correctly. It will be really useful have creact-react-app setting up things correctly, because right now there are some confusing directions on the few guides available.

**Comment by necolas** [comment]
Sounds like you might not be telling webpack where to find the config file

**Comment by ararog** [comment]
Wierd, I'm doing exactly like docs, on root of project I'm executing almost same command as in the getting started guide: `./node_modules/.bin/webpack-dev-server -d --config web/webpack.config.js --inline --hot --colors`

**Comment by Stas-Buzunko** [comment]
confirm @ararog , having the same issue with alias

**Comment by necolas** [comment]
The next minor release – 0.3.0 – will include a new package `babel-plugin-react-native-web` that will unblock this task.

> Configure the preset…

It's a plugin rather than a preset

**Comment by necolas** [comment]
If someone wants to take this on and add it to the next release of CRA… https://github.com/facebookincubator/create-react-app/issues/3672

**Comment by tanneess** [comment]
Looks to me like it is already part of it no? 
This was merged in master on august 2016 
https://github.com/facebook/create-react-app/pull/407

But maybe I missed something ;)

**Comment by paularmstrong** [comment]
In progress at: facebook/create-react-app#4125

**Comment by necolas** [comment]
Thanks. Closing this tracking issue
