### ISSUE TITLE
Expo compatibility

### ISSUE THREAD

**Issue by nikolal** [necolas/react-native-web#699]
Is there a plan to integrate this project with Expo?

Can it be integrated without ejecting Expo app?

**Comment by rickiesmooth** [comment]
I'm using the Expo app and RNW, when you require stuff from the expo package in RNW it throws errors, I was able to just not require expo specific packages on the web.

**Comment by walleXD** [comment]
Expo include a lot of expo specific libraries with React Native. You can't just pick up an app and use it with RNW as otherwise you would have to polyfill the expo packages you are using. The best approach is to take an universal component, where the presentation components are shared, while keeping the containers in their own projects

**Comment by nikolal** [comment]
OK. Thanks, I will close this.
