### ISSUE TITLE
How is ResponderEventPlugin used?

### ISSUE THREAD

**Issue by gaearon** [necolas/react-native-web#739]
Sorry for a naïve question.

I'm curious how much this project depends on `ResponderEventPlugin`. Is it absolutely essential? Does it depend directly, or only because other RN ecosystem packages need it?

**Comment by necolas** [comment]
It is used directly by the [touchables](https://github.com/necolas/react-native-web/blob/master/src/components/Touchable/Touchable).js and PanResponder, but those event callbacks are part of the View API itself

**Comment by gaearon** [comment]
Do you see any potential way forward if we were to disallow injecting plugins into ReactDOM?

**Comment by necolas** [comment]
Not off the top of my head if plugin injection is still part of React Native's implementation

**Comment by gaearon** [comment]
Would checking in `react-dom` as a git submodule and then forking some files be too much of a burden? We could make it easy for you to fork individual files in the build process, e.g. by letting you run `yarn build --forks=myforks.js` to override [this file](https://github.com/facebook/react/blob/master/scripts/rollup/forks.js) that *we* use for forking.

**Comment by gaearon** [comment]
Another question is would it be possible to re-implement `View` (do you do it anyway?) and keep its existing API, but implement `onResponder*` callbacks in userland (e.g. by tracking JS events right in `View.js`)?

**Comment by necolas** [comment]
One issue is the impact on apps that use RNW - you don't want to risk including both ReactDOM and a fork of ReactDOM in your bundle. For example, some parts of Twitter Lite are still built on ReactDOM and that's not a problem at the moment because React Native for Web is also built on ReactDOM. If you wanted to migrate an existing "ReactDOM app" to the React Native API, that would be quite painful and costly for users if RNW required its own forked renderer. And any dependency that relies on ReactDOM would immediately add another 35KB to your bundle (and maybe cause other issues?)

My initial thoughts are that moving the work into `View` wouldn't be practical as RN implements this at the level of the event system. If the `ResponderEventPlugin` were unnecessary, I'd expect React Native to be able to remove it too. Otherwise I think this would make it harder to unify web/native development around a common set of primitives, when it's already a challenge massaging the differences between the events in ReactDOM and React Native.

If React Native can't drop the Responder system, could another potential way forward for now be to include a bundle in the ReactDOM package that includes the Responder event system? Then perhaps the RNW Babel plugin could rewrite imports to point to that. It could still be problematic for users, as it would make Babel and hard requirement and most web apps don't run Babel over their `node_modules` dependencies.

**Comment by gaearon** [comment]
Is it expected that RNW users can use *both* packages targeted at `react-native` (and importing things like `View`) and packages targeted at `react-dom` (and importing things like `findDOMNode`)?

**Comment by necolas** [comment]
Yes. Interop is currently essential given how much of the ecosystem was built on React DOM over the last few years

**Comment by necolas** [comment]
Going to close this issue but please don't take that to mean we can't continue the discussion here :)
