### ISSUE TITLE
StyleSheet: singleton is not reset on the server

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#778]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Looks like the StyleSheet accumulates styles across requests, which can result in excess initial CSS being inlined for individual screens in a chunked app.

**What is the expected behavior?**

Fresh StyleSheet / minimal styles for each SSR

**Environment (include versions). Did this work in previous versions?**

* OS: all
* Device: all
* Browser: all
* React Native for Web (version): all
* React (version): 16

**Comment by MoOx** [comment]
Indeed, I faced this with Phenomic SSR but never took the time to open an issue :)

**Comment by necolas** [comment]
Are you getting the styles using `AppRegistry.getApplication()` or `StyleSheet.getStyleSheets()`? I'm thinking of removing `StyleSheet.getStyleSheets()`.

**Comment by necolas** [comment]
Interested in testing out some improvements to StyleSheet?

You can build this WIP branch – [stylesheet-refactor](https://github.com/necolas/react-native-web/tree/nicolas/react-native-web/stylesheet-refactor) – which I'm hoping will fix SSR, speed up startup, and bring support for `TextInput.props.placeholderTextColor` and animation keyframes. The API has changed but it should be clear how to use it from the patch (and even a bit simpler).

The specific patch related to SSR styles being a function of the render tree is https://github.com/necolas/react-native-web/commit/f0899e5844ef3c7ed2ee4c91eab301402e9c082c

**Comment by MoOx** [comment]
`StyleSheet.getStyleSheets()` can be handy in case you can't use `AppRegistry.getApplication()`. At least we should keep an escape hatch to be able to retrieve styles without AppRegistry.

**Comment by necolas** [comment]
What's the problem with using `AppRegistry`?

**Comment by MoOx** [comment]
No real problem, but depending your env, you may have something else doing the rendering, not aware of the fact that your use RNW (eg: static site generator like gatsby or phenomic etc)

**Comment by necolas** [comment]
What's an example of what gatsby or phenomic need to do that they can't do with `AppRegistry`?

**Comment by MoOx** [comment]
The problem (at least for phenomic) is that there is a generic renderer for react that rely on ReactDOM(server). If we want to use AppRegistry, this will require specific RNW code or another RNW renderer (not impossible, but if that's "just" to `render`, it does not really seems legit - at least without knowing what's important about AppRegistry).

What is so important that `AppRegistry` handles that cannot be done otherwise?

**Comment by necolas** [comment]
`AppRegistry` doesn't do any rendering for you. You still use ReactDOMServer in your app for that.

**Comment by MoOx** [comment]
I used "ReactDOM(server)" to mean that both client & server methods are used. toStaticMarkup and hydrate/render. At least for static renderer it's a bit tricky cause you need to be aware of the routing etc.
In the case of phenomic, phenomic accepts routes and handle the rendering step (if you are curious, https://github.com/phenomic/phenomic/blob/92acf0d87ad889fca74c6f72a3219d0d8bf1d3e6/packages/plugin-renderer-react/src/createApp.js).

I am just afraid that making `AppRegistry`mandatory make it's difficult (or at least add extra work/plugins/whatever) for RNW users that want to use phenomic without extra work (myself included haha).

**Comment by necolas** [comment]
You linked to a client-side file. I looked through both server and client rendering code and I still don't understand the problem.

Do you mean that you don't want to change the client side setup to rely on AppRegistry to render? Why not? Wouldn't you need to customize that in some way for any css-in-js library? They all use providers or some API to extract styles.

**Comment by MoOx** [comment]
> Why not?

Because like you said, I don't want to customize for all css-in-js lib. I think I found a better API that let users handle their final rendering without having to deal with the toStatic/hydrate step.

Some examples:

- https://github.com/phenomic/phenomic/blob/92acf0d87ad889fca74c6f72a3219d0d8bf1d3e6/examples/react-app-styles-with-aphrodite/Html.js#L5-L7
- https://github.com/phenomic/phenomic/blob/92acf0d87ad889fca74c6f72a3219d0d8bf1d3e6/examples/react-app-styles-with-glamor/Html.js#L5-L6
- https://github.com/phenomic/phenomic/blob/92acf0d87ad889fca74c6f72a3219d0d8bf1d3e6/examples/react-app-styles-with-styled-components/Html.js#L5-L6

In practise for RNW, here is how it looks like https://github.com/phenomic/phenomic/blob/92acf0d87ad889fca74c6f72a3219d0d8bf1d3e6/docs/Html.js#L15-L20
(I should add it as an example btw)

I found this more elegant for end user to "just" have to tweak a file (can even allow to mix multiple libraries) with lib specific code rather than have to use a single plugin (or multiple) that will require a weird codebase to be able to mix all this things together.

Keeping a similar API for RNW would be great but I will understand your position if you are not open to.

**Comment by necolas** [comment]
What about this?

```js
import * as React from "react";
import Head from "react-helmet";
import { AppRegistry } from "react-native-web";

const Html = ({ App, render }: PhenomicHtmlPropsType) => {
  AppRegistry.registerApplication('App', () => App);
  const app = AppRegistry.getApplication('App');
  const { Main, State, Script, Style } = render(app.element);
  const helmet = Head.renderStatic();
  return (
    <html {...helmet.htmlAttributes.toComponent()}>
      <head>
        {helmet.meta.toComponent()}
        {helmet.title.toComponent()}
        {helmet.base.toComponent()}
        {app.getStyleElement()}
        <Style />
        {helmet.link.toComponent()}
        {helmet.style.toComponent()}
        {helmet.script.toComponent()}
        {helmet.noscript.toComponent()}
      </head>
      <body {...helmet.bodyAttributes.toComponent()}>
        <Main />
        <State />
        <Script />
      </body>
    </html>
  );
};

export default Html;
```

**Comment by MoOx** [comment]
Looks good!

**Comment by necolas** [comment]
No more worries about using `AppRegistry`? If you could give it a try and let me know if this issue is avoided, that would be great

**Comment by MoOx** [comment]
This code above can be easily overridden by the user (and recommended), so it's not a problem here. Will try that and get back to you.
