### ISSUE TITLE
TextInput 'textAlign' style property doesn't work on the input-tag and generates warning

### ISSUE THREAD

**Issue by IjzerenHein** [necolas/react-native-web#81]
When setting the 'textAlign' style for a TextInput, the following warning is generated:

```
Warning: Failed propType: Invalid props.style key `textAlign` supplied to `View`.
```

Also, the placeholder text is aligned correct, however the value inside the `<input>` is not.

To reproduce:

```
<TextInput style={{textAlign: 'center'}} />
```

I would love to this fix this myself, however I don't quite understand the architecture of the TextInput component fully yet. Would replacing `<View>` at the root of the render function by `<CoreComponent>` solve the problem?
I'd love to gain some insights into the inner workings and contribute my part where possible.

cheers

**Comment by necolas** [comment]
Yeah using `CoreComponent` can side-step the View API. That might not be what we want to do though, if `TextInput` is to maintain the existing API. I'll take a look at this because there are a lot of text-only styles that are currently accepted by `TextInput`, but which are applied to an inner `View`.

**Comment by IjzerenHein** [comment]
Awesome! If I need to help testing anything let me know.
