### ISSUE TITLE
Test setup

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#83]
- [ ] look into using https://github.com/airbnb/enzyme for shallow rendering where possible
- [ ] look into whether testing in real browsers is critical, or whether we should switch to jest to better align with FB react projects

**Comment by MoOx** [comment]
For shallow rendering, there is also things iike [expect-jsx](https://github.com/algolia/expect-jsx) and a [lot of similar tools](https://github.com/algolia/expect-jsx#similar-projects) depending on your test runner.
[Not sure that testing onClick and other event is relevant](http://putaindecode.io/en/articles/js/react/unit-testing/) since it's probably covered by React test suite.

**Comment by MoOx** [comment]
I am currently using some very simple helpers for shallow rendering https://github.com/MoOx/jsx-test-helpers (because I found enzyme is overkill - and I really don't like the jquery like syntax).
