### ISSUE TITLE
Benchmarks on the website

### ISSUE THREAD

**Issue by JayAndCatchFire** [necolas/react-native-web#836]
I really like the [benchmarks page](http://necolas.github.io/react-native-web/benchmarks/) you've got.  However, I've noticed a few issues.

- There might be some sort of memory leak or something because the more benchmarks you run the slower everything gets.  It affects the benchmarks significantly.  Leaving the tab idle in the background a while should show the symptoms.  I'm using Chrome 64.0.3282.186.
- aphrodite is missing an "update dynamic styles" implementation
- There might be something wrong with the "update dynamic styles" implementation for styled-jsx as it looks bizarre on load (although running the benchmark looks okay).
- There's no implementation for [glamorous](https://github.com/paypal/glamorous).

If I find some time in the next few days, I'll try to address these with some PRs, if that's okay.

**Comment by necolas** [comment]
I can't reproduce the claimed memory leak. Aphrodite can't implement the dynamic styles benchmark as it has no support for dynamic styles. I think styled-jsx is just a bit buggy (some libraries don't adequately namespace their class names, I've mentioned to the authors but they haven't fixed it). And I'm not adding an implementation for glamorous as it depends on glamor, which is already included.

**Comment by JayAndCatchFire** [comment]
I got it to happen again.
<img width="1703" alt="screen shot 2018-02-26 at 5 21 47 pm" src="https://user-images.githubusercontent.com/10983817/36701652-d1c1614c-1b19-11e8-814d-f99639225f2f.png">

**Comment by necolas** [comment]
I think that's a [known issue](https://github.com/emotion-js/emotion/commit/5275011338fcbd798bd844b7ae2f0b86545559fc#r27025823) with glamor and emotion generating MB's of CSS for the dynamic styles test. After you run the glamor dynamic styles case, the browser is dying and everything after that is slow. There used to be a note about this in the benchmarks README:

> ‡Glamor essentially crashes the browser tab. Emotion gets slower every iteration.
[Source](https://github.com/necolas/react-native-web/blob/3e1b68d801b3e54fe58e62f6ed012d8989bf8010/packages/benchmarks/README.md)

You can tell it's an issue in the browser because the Script/Layout (S/L) timings indicate that all the time is spent in the browser performing layout, which is very slow because there is probably about 6 MB of total CSS generated by then.

I might remove the dynamic benchmarks for emotion and glamor to avoid this confusion, because unless you understand the details of what those libraries are doing, it's not obvious what the cause is.

**Comment by JayAndCatchFire** [comment]
Awesome, thanks for the helpful info.

**Comment by necolas** [comment]
You're welcome!
