### ISSUE TITLE
Any "Good" Navigation solutions for cross-platform [android/web] project?

### ISSUE THREAD

**Issue by VilleKokkarinen** [necolas/react-native-web#916]
Are there any "good" Navigation solutions when creating a cross-platform application with android, web (and possiby IOS), while sharing codebase from a existing RN-App (Latest React, RN etc.. versions).

Was currently using router-flux as the main router for a native-only project, and managed to get all the screens to render properly "on the web", but the routing didn't work at all. (AFAIK router-flux doesn't support web at all).

*Tried react-navigation & react-router also, but they just kept spitting errors, and refused to compile at all. (probably because of invalid versions with React, R-N, & RNW, and or webpack misconfig.)

**Comment by necolas** [comment]
This is a question you could ask on stackoverflow or reactiflux. Not something I've got an opinion about

**Comment by vladp** [comment]
@VilleKokkarinen  I have no problems mixing react-router, react-native-web, react-bootstrap together to get a navigation bar and to navigate back/forth between my screens.

There were no changes and no 'ejections' that I had to do an application created with create-react-app, to get RNW and react-router (v4) to compile and work together.

Even more, I had not seen any problems mixing react native web, with react-bootstrap, react-router, react-native-vector-icons. 
This shows, that React-native-web works well with components from Native world and from Web world, as long as those components/libraries themselves support web browser deployments.


I do not yet have , react-router (or react-native-router) fully replacing my RN-side navigation, where I am using [depreciated React Native Navigator](https://www.npmjs.com/package/react-native-deprecated-custom-components) .
I am also leaving the possibility that I will end up with 2 different navigation models, one for web and one for native.
I did note, that there simply not enough 'functions' to just get all things working for navigation.
So I introduced into my setup, a light weight no-external-dependencies pub sub library:  [pubsub-js](https://www.npmjs.com/package/pubsub-js).  This way I can trigger re-renders of my React-native-web screens , by subscribing to pub events that are coming from my navigation buttons (that I implemented using react-bootstrap navigation menu and backed by react-bootstrap ).

Other people may choose to use react-redux, rather than pubsub-js -- but for my needs, so far pubsub-js has been really good to provide event-based linkage between unrelated or deeply hierarchical components.

As necolas rightly pointed, on this, and other replies -- React-Native on its own does not implement a navigation solution. So this is not something that react-native-web will implement, or provide an opinionated integration for.

**Comment by virtualirfan** [comment]
FWIW, I asked a similar question re: react-navigation on discord and brentvatne responded as such:
```
brentvatne - Yesterday at 5:30 PM
it actually already works, you can run create-react-native-app SomeApp --with-web-support and install react-navigation there and use it
```
Haven't tried it yet. YMMV. As @necolas says, try discord for more specific questions re: react-navigation or other nav RN solutions out there.

**Comment by luandro** [comment]
Isn't as simple as that. I've tried and I ran into errors that are discussed on this [issue](https://github.com/necolas/react-native-web/issues/801) and there's also an article: [Using React Native, React Native Web and React Navigation in a single project](https://pickering.org/using-react-native-react-native-web-and-react-navigation-in-a-single-project-cfd4bcca16d0). I'll follow and see if I can get it to work.

**Comment by Mbouendeu2015** [comment]
@luandro  did you get it work ? Cuz me too i have already run into millions of errors and still no solutions is perfectly working for me...single screens is popping but navigation get me stuck

**Comment by luandro** [comment]
@Mbouendeu2015 I ended up using https://github.com/vincentriemer/react-native-dom which has it's own quirks, but it worked out for me.

**Comment by Mbouendeu2015** [comment]
please @luandro  did you use it with react-native-web or by itself

**Comment by andy-root** [comment]
React Navigation uses native modules, I'm new react-native-web, but if a package requires a native module how can it be used for web?

**Comment by leggomuhgreggo** [comment]
I think most people use react-navigation and just branch for web. I used [redux-first-router](https://github.com/faceyspacey/redux-first-router) (now rudy) but YMMV.
