### ISSUE TITLE
Hydrate method for development

### ISSUE THREAD

**Issue by codejamninja** [necolas/react-native-web#918]
Can we switch the render method to hydrate in development mode?

Refer to issue #733

**Comment by necolas** [comment]
See #745

**Comment by necolas** [comment]
What's going to be deprecated?

**Comment by English3000** [comment]
"Because React is backwards compatible, `render()` will continue to work when rendering on top of server-generated markup in React 16, but you should change those calls to `hydrate()` to quiet the warning and prepare your code for React 17."

See here: https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67

**Comment by necolas** [comment]
`render` isn't being deprecated though. You still use it when not hydrating server-rendered markup. 

This issue doesn't explain what the problem is. Just that there's a warning in development if you're using SSR? I don't think there's much I can do about that, as either way is going to produce a warning for someone and dev-time SSR is the less common case.

**Comment by codejamninja** [comment]
Ok, cool. Thanks for the explanation.
