### ISSUE TITLE
Update 'Animated'

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#95]
Either with RN patches: https://github.com/facebook/react-native/commit/ae0ad1fc7e8d7a591b5b1c0789c39bdcdfd3f388

Or with: https://github.com/animatedjs/animated

**Comment by necolas** [comment]
This is not as simple as it was the first time, as RN has added patches for native-specific concerns like https://github.com/facebook/react-native/commit/65ccdffc8d948073e03fd792ec080f8a9a7cc93a. It looks prohibitively expensive to patch RN's `Animated` for web now; I'm wondering what the status of animatedjs/animated is and if we should try using that instead?

cc @vjeux @lelandrichardson

**Comment by lelandrichardson** [comment]
@necolas all of the changes should be internal only... the only external API surface area that has been added is that people can pass in `useNativeDriver: true` in the config of `Animated.spring`/`Animated.timing` etc., which in the case of Web should probably just "continue as normal" and ignore that flag.

It would be nice though if this project depended on `animatedjs/animated`, so that we can minimize "alternate" implementations that are in the wild.  You can see how i'm doing this in `react-primitives` for reference. It should be pretty much plug & play.

**Comment by necolas** [comment]
Thanks for the suggestion; it was indeed easy :)
